### ISSUE TITLE
Switch to pure go

### ISSUE THREAD

**Issue by moshloop** [kubernetes/repo-infra#123]
Bash and python work well in a monorepo like k/k, but the developer experience for vendoring/git subtree is far from optimal with the repository explosion occurring in kubernetes-sigs at the moment

There are many go tools and libraries (like https://github.com/google/addlicense / https://github.com/fbiville/headache )  that can be vendored into this repo and then published as a single, tested binary for consumption

xref: https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/23

**Comment by BenTheElder** [comment]
Hmm....

Some of the up to date reusable tools in this repo include tools in go and bazel rules (skylark) that are depended on by github.com/kubernetes/kubernetes

Who is actually using these bash scripts in this repo today? Most repos I've seen including kubernetes have their own set of scripts rather than the ones in this repo, however kubernetes does depend on some of the other tooling (like kazel).

> that can be vendored into this repo and then published as a single, tested binary for consumption

why would it be a single binary? if I need a fix to any of these tools I must now update all of them? and if I only use some of them I must download a binary for all of them?
is kazel part of this single binary?

**Comment by moshloop** [comment]
This tool doesn't necessarily need to be based on the scripts in this repo, or live in this repo just that this seems the most logical place to start the discussion

> Most repos I've seen including kubernetes have their own set of scripts 

That's kind of the problem, there are dozens or hundreds of these scripts floating around, without a commonplace to implement new features and fix issues.

> why would it be a single binary? 

Doesn't necessarily have to be a single binary, but it would be much easier to use

> is kazel part of this single binary?

No, the binary replaces the bash scripting only, e.g.

`repo-infra --kazel=1.0 --controller-runtime=1.0 lint|check-headers|generate-docs` 

`repo-infra` would then download the required dependency and invoke it as appropriate

**Comment by neolit123** [comment]
> kubernetes/bash-firefighters

lol, nice team name.

> That's kind of the problem, there are dozens or hundreds of these scripts floating around, without a commonplace to implement new features and fix issues.

this is a problem yes.

having a single repo that hosts all verify* code (via a go or bash), makes sense until repos start requiring customizations for things as simple as verify-gofmt.sh - e.g. how to customize skipping a folder?

i've discussed this with @chuckha and i personally think that it's not that easy to achieve.
a core repo needs to host a set of tools that allow a number of knobs via e.g. ENV vars, so this means that repos that use the core repo need more bash scripts with the customizations.

still better than duplicating the same code around.

so doable, but someone needs to invest the time into architecting this, getting a stamp and working on it.
