### ISSUE TITLE
Support rules_docker

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/repo-infra#207]
kubernetes/kubernetes `rules_docker` (`0.7.0`) is pretty out of date compared to `0.14.4`.
It probably be helpful if `rules_docker` was managed here instead.

/kind feature
ref: https://github.com/kubernetes/kubernetes/pull/93981, https://github.com/kubernetes/kubernetes/pull/93888#issuecomment-673735529
cc: @BenTheElder

**Comment by BenTheElder** [comment]
it does seem like upgrading repo_infra might get increasingly dicey as it implies upgrading more third party rules

**Comment by LappleApple** [comment]
Comment from triage: folks aren't 100% clear what `rules_docker` is. Is there a way to find this information (a link, for ex.) so that others might be able to help work on it?

**Comment by dims** [comment]
we don't have to worry anymore since kubernetes/kubernetes has gotten rid of bazel.

/close
