### ISSUE TITLE
_go_genrule_impl fails in some build environments because it tries to `mv` a source file

### ISSUE THREAD

**Issue by jmillikin-stripe** [kubernetes/repo-infra#211]
The following Bazel action fails when the build environment does not allow source files to be deleted or removed:
```starlark
ctx.actions.run(
    executable = "mv",
    arguments = [args],
    inputs = [srcfile],
    outputs = [target],
    mnemonic = "PrepareGopath",
)
```

I recommend using either `executable = "cp"`, or switching to `ctx.actions.expand_template()` to avoid the process spawn entirely.

**Comment by justaugustus** [comment]
@jmillikin-stripe -- would you like to submit a PR for this?

**Comment by jmillikin-stripe** [comment]
I am slightly buried at the moment and don't have time to navigate the Kubernetes PR process, but here is the one-line patch that is confirmed to fix the issue in Stripe's build environment:
```diff
diff --git a/defs/go.bzl b/defs/go.bzl
index 8b055d7..f918beb 100644
--- a/defs/go.bzl
+++ b/defs/go.bzl
@@ -49,7 +49,7 @@ def _go_genrule_impl(ctx):
             args.add(target.path)
 
             ctx.actions.run(
-                executable = "mv",
+                executable = "cp",
                 arguments = [args],
                 inputs = [srcfile],
                 outputs = [target],
```

**Comment by justaugustus** [comment]
Thanks! Opened https://github.com/kubernetes/repo-infra/pull/213 for this.
