### ISSUE TITLE
verify-boilerplate: please be more user-friendly

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/repo-infra#231]
There are explicitly allowed boilerplate headers for different file extensions in this repo. However, there is no `bazel` target to inject them where they are not found, for automatic updates. Similarly, the tool doesn't even tell you _why_ a header is wrong:

```
$ bazel run @io_k8s_repo_infra//hack:verify-boilerplate
INFO: Analyzed target @io_k8s_repo_infra//hack:verify-boilerplate (1 packages loaded, 247 targets configured).
INFO: Found 1 target...
Target @io_k8s_repo_infra//hack:verify-boilerplate up-to-date:
  bazel-bin/external/io_k8s_repo_infra/hack/verify-boilerplate
INFO: Elapsed time: 1.140s, Critical Path: 0.06s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from @io_k8s_repo_infra//hack:verify-boilerplate
-----------------------------------------------------------------------------
1 files have incorrect boilerplate headers:
hack/analyze-memory-profiles.py
```

This is pretty unfriendly to users. My header was wrong in the python file because of a difference in whitespace, so it was impossible to know what was wrong until I copy-pasted in the correct header from this repo. 

It would be good if:

 - there existed a `bazel` target to update files to contain the correct boilerplate
 - the verify target showed you the diff between what you had and what you needed
 - the verify target told you how to run the update target

cc @cpanato @fejta

**Comment by cpanato** [comment]
sorry for the delay to reply, agree to have an option to add the boilerplate.

will check how to add that

**Comment by cpanato** [comment]
/remove-lifecycle rotten

need to find a time to finish this :(
