### ISSUE TITLE
Enable verifying copyright headers via `goheader`

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/repo-infra#248]
As he invariably does, @edwarnicke pointed me to an awesome linter from @denis-tingaikin: `goheader`
- https://github.com/denis-tingaikin/go-header
- https://golangci-lint.run/usage/linters/#goheader

For Golang repos (maybe all repos), we can use this to remove a dependency on k/repo-infra!

See some examples here:
- https://github.com/networkservicemesh/sdk/blob/6d5254af4bb4ba91c8ff74c0e506f64396339966/.golangci.yml#L8-L14
- https://github.com/networkservicemesh/sdk/tree/6d5254af4bb4ba91c8ff74c0e506f64396339966/.ci/license

cc: @kubernetes/release-engineering 
/help
maybe:
/good-first-issue

**Comment by cpanato** [comment]
i will take a look on this, and maybe we can start using that with release-sdk/utils and so on

**Comment by cpanato** [comment]
was running that, and the go-header expect the year (if we set the year) to be the current year for the header

```
env/internal/impl.go:1:11: Expected:2022, Actual: 2021 The Kubernetes Authors. (goheader)
/*
  ^
```

**Comment by edwarnicke** [comment]
@cpanato I believe only if the files changed in this PR.  We use it and it will absolutely complain about changed files and their year not being current (or current year being in range)... but unchanged files it leaves alone.  @denis-tingaikin care to say more?

**Comment by cpanato** [comment]
@edwarnicke thanks, I ran that locally and it complained all the files, will try it again
I was using that together with golangci-lint

**Comment by edwarnicke** [comment]
@cpanato One other thought that occurred to me.  Which version of golanglint-ci are you running?

**Comment by cpanato** [comment]
> @cpanato One other thought that occurred to me. Which version of golanglint-ci are you running?

the latest 1.44.0

**Comment by edwarnicke** [comment]
@cpanato Could you point me to the repo you are running against (and a PR for what you are doing there) so I can try to reproduce what you are seeing?

**Comment by cpanato** [comment]
> * https://github.com/denis-tingaikin/go-header

i was using the https://github.com/kubernetes-sigs/release-utils

I see how the go-header works now, if I touch in an existing file we will need to update the year of the header, but this is not the pattern we have in k8s, afaik the year in the header is the year when the file was first created, not modified.

also for generated go files we don't add an year

**Comment by denis-tingaikin** [comment]
@cpanato Note: year of creation is const and should be not changed. With option `{{year-range}}` you could change the year-range for touched files. Something like `${year-of-file-creation}-${currenty-year}`.

Moreover `{{year-range}}` is a builtin pattern, you also can create your own option for your cases.


Question1: Could you please say more about use cases?

Question2: Is this config would be good for you?

```
  goheader:
    template-path: "scripts/boilerplate/boilerplate.go.txt"
    values:
      regexp:
        copyright-holder: Copyright {{year-of-file-creation}} The Kubernetes Authors.
```

**Comment by cpanato** [comment]
> @cpanato Note: year of creation is const and should be not changed. With option `{{year-range}}` you could change the year-range for touched files. Something like `${year-of-file-creation}-${currenty-year}`.
> 
> Moreover `{{year-range}}` is a builtin pattern, you also can create your own option for your cases.
> 
> Question1: Could you please say more about use cases?
> 
> Question2: Is this config would be good for you?
> 
> ```
>   goheader:
>     template-path: "scripts/boilerplate/boilerplate.go.txt"
>     values:
>       regexp:
>         copyright-holder: Copyright {{year-of-file-creation}} The Kubernetes Authors.
> ```
> 
> Note: {{year-of-file-creation}} is not added yet, but it can be added for the next version of the tool.

Question1: we have two types of go files, the ones humans create and those we set the header copyright with the year that was created and that most likely will not change (maybe will change if there is a license change)
and the other type is the ones that are generated using go generate or other tools, and those will change over time, for those we don't set a year in the header that is blank.

question2: that looks good, but I think that does not fit the second case I've described above, the ones that are generated by a generator tool

btw, thanks so much for jumping on that and I can help in the project if needed, just let me know, I did not know about this project but I love it

**Comment by cpanato** [comment]
@denis-tingaikin cool, thanks it is working the check now. please let me know when have the new feature and where i can help

thanks again for the support! 🎉
