### ISSUE TITLE
go get kazel does not work

### ISSUE THREAD

**Issue by rickypai** [kubernetes/repo-infra#33]
according to the documentation,

`$ go get k8s.io/repo-infra/kazel` should just work but I get this message:

```
$ go get k8s.io/repo-infra/kazel
package k8s.io/repo-infra/kazel: unrecognized import path "k8s.io/repo-infra/kazel" (parse https://k8s.io/repo-infra/kazel?go-get=1: no go-import meta tags ())
```

some info:

```
$ go version
go version go1.8.3 darwin/amd64
```

**Comment by ixdy** [comment]
Yeah, I never set up the go import paths on k8s.io for repo-infra. I should probably do that.

In the meantime, you can `go get github.com/kubernetes/repo-infra/kazel`. (Though the bazel scripts in `kubernetes/kubernetes` download and install the correct version of `kazel` for you, so you shouldn't need to manually `go get` it ever.)
