### ISSUE TITLE
kazel should write non-error output to stdout

### ISSUE THREAD

**Issue by thockin** [kubernetes/repo-infra#36]
```
$ ./hack/update-bazel.sh >/dev/null
wrote "BUILD.bazel"
```

tssk tssk.

**Comment by ixdy** [comment]
I think we do this to differentiate from the diff output, which gets written to stdout, though I'm not sure.

**Comment by thockin** [comment]
or maybe a `--silent` flag ?

**Comment by thockin** [comment]
Still true

/lifecycle frozen
/remove-lifecycle stale

**Comment by fejta** [comment]
IMO anything humans should consume should go to stderr. Anything that should be piped to a subsequent process should be stdout

**Comment by thockin** [comment]
I'm not going to debate here, it's a minor point, but I'm going to
disagree.  `foo --help | less` should work.

**Comment by fejta** [comment]
```bash
go help modules 2> /dev/null`
go --help 2> /dev/null
```

**Comment by fejta** [comment]
Agree with the intent of being able to read help output. Also agree that tools have ways (`--silent`) to be less noisy. I don't think this conflicts with the principle outlined above.

Given `kubectl get foo --random-flag`:
* the foo output belongs on stdout (that's what the command is requesting)
* Everything else is for a debugging human and therefore belongs on stderr, such as
  - `connecting to server, please wait...`
  - `foo not found` 
  - `unrecognized flag: --random-flag` (and/or docs telling me how to use `kubectl get`)

Given `kubectl help get --full`
* the get help output belongs on stdout (that's what's requested)
* Everything else belongs belongs on stderr
  - `unknown command: get`
  - `bad flag: --full`
  - `checking server for available updates...`
  - `extracting man tarball...`

This is essentially how to go binary works (although one might want to special case --help, which it doesn't)

**Comment by thockin** [comment]
I agree with what you say.  Whatever the user asked for goes to stdout.
Period.
