### ISSUE TITLE
Rolling update for statefulset is NOT working

### ISSUE THREAD

**Issue by db-vmw** [kubernetes/repo-infra#44]
Hi,
'm following the document: " https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets " for updating my statefulset to use new image version (rolling update).

On issuing the command:
kubectl patch statefulset my_statefulset_name -p '{"spec":{"updateStrategy":{"type":"RollingUpdate"}}}'
Output: my_statefulset_name patched.

On issuing the command:
kubectl patch statefulset my_statefulset_name --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"my_image"}]'
Output: my_statefulset_name patched

But, nothing happens, I don't see any pods recreating with the new image mentioned. What's happening here? Where to find the logs on what's going wrong here? kubectl describe pod was not helpful.

Note:
 If I manually delete the pods, the new pods comes up with new image specified as part of patch command. Is this the expected behavior?

After running the command,
kubectl patch statefulset my_statefulset_name --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"my_image"}]' , I do see the stateful set my_statefulset_name updating with the new image ID
(i.e. kubectl describe statefulset my_statefulset_name shows the "my_image" (new image specified). But, the pods doesn't update themselfs to the new image mentioned (my_image)

Yaml file refers to apiVersion: apps/v1beta1

**Comment by ixdy** [comment]
This is probably the wrong repo for this issue. You may want to try opening an issue in kubernetes/kubernetes, if you did not already.

/close
