### ISSUE TITLE
support debs in tools/build_tar

### ISSUE THREAD

**Issue by ixdy** [kubernetes/repo-infra#61]
I think then we'd be able to swap it in for the python-based archiver building docker images, which should make the kubernetes build even faster.

cc @mikedanese @mattmoor 

(also at some point we should consider contributing our fast build_tar upstream. maybe the new bazelbuild/rules_pkg repo?)

**Comment by ixdy** [comment]
More background info: it looks like the current packager for `docker_build` is https://github.com/bazelbuild/rules_docker/blob/master/container/build_tar.py, though you can swap it out by adding `build_layer = "@io_kubernetes_build//tools/build_tar"` to your `docker_build` rule. (Which doesn't work right now, due to missing deb functionality.)

**Comment by ixdy** [comment]
It looks like debian files use `ar`, and from some quick searches there appear to be some go libraries already supporting it.

**Comment by serathius** [comment]
Started working on it

**Comment by BenTheElder** [comment]
Adding a note that I've been experimenting with bazel remote caching and building the tarballs doesn't cache well (since they depend on the rest of the build) and they're pretty slow right now, this would be an *excellent* thing to speed up.

**Comment by ixdy** [comment]
note that we do already use the fast tar builder for most of the tarballs, but the docker image building is not currently using it.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
there's still a PR out for this IIRC 😬
